# Configuration for the MSAL (Microsoft Authentication Library) Exchange Handler, managing token exchange and session cookies.
# Indicates if the MSAL Exchange is enabled.
enabled: ${msal-exchange.enabled:true}
# The new path your React SPA will call with the Microsoft token.
exchangePath: ${msal-exchange.exchangePath:/auth/ms/exchange}
# The logout path can remain the same.
logoutPath: ${msal-exchange.logoutPath:/auth/ms/logout}
# The domain to use for the session cookie.
cookieDomain: ${msal-exchange.cookieDomain:localhost}
# The path to use for the session cookie.
cookiePath: ${msal-exchange.cookiePath:/}
# If the session cookie should be marked as secure (requires HTTPS).
cookieSecure: ${msal-exchange.cookieSecure:false}
# Session timeout in seconds. This is the time after which the session will expire.
# Default is 3600 seconds (1 hour).
sessionTimeout: ${msal-exchange.sessionTimeout:3600}
# Remember me timeout in seconds. This is the time after which the session will expire
# if rememberMe is set true during login. Default is 604800 seconds (7 days).
rememberMeTimeout: ${msal-exchange.rememberMeTimeout:604800}
